"""empty message

Revision ID: 147cc7c700dd
Revises: 2b1d22f7435f
Create Date: 2023-09-07 10:12:48.648491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147cc7c700dd'
down_revision = '2b1d22f7435f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_siswa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_siswa', schema=None) as batch_op:
        batch_op.drop_column('id_card')

    # ### end Alembic commands ###
