"""empty message

Revision ID: 1cc66d7082ec
Revises: efc8781a757a
Create Date: 2023-10-11 10:55:44.166349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc66d7082ec'
down_revision = 'efc8781a757a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_notifikasi_siswa', schema=None) as batch_op:
        batch_op.drop_constraint('data_notifikasi_siswa_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detail_siswa', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_notifikasi_siswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_notifikasi_siswa_ibfk_1', 'detail_siswa', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
