"""empty message

Revision ID: 2b1d22f7435f
Revises: 8e9eae5bc55c
Create Date: 2023-09-04 08:13:42.197962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1d22f7435f'
down_revision = '8e9eae5bc55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telp', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_admin', schema=None) as batch_op:
        batch_op.drop_column('telp')

    # ### end Alembic commands ###
