"""empty message

Revision ID: 2bd9e6f60f5b
Revises: 362e7caccf37
Create Date: 2023-08-22 13:35:41.049799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd9e6f60f5b'
down_revision = '362e7caccf37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_constraint('data_pembinaan_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_pelanggaran', ['pelanggaran_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_pembinaan_ibfk_2', 'data_pelanggaran', ['pelanggaran_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
