"""empty message

Revision ID: 362e7caccf37
Revises: 8c698d02e5e3
Create Date: 2023-08-21 09:12:42.343761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362e7caccf37'
down_revision = '8c698d02e5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.alter_column('tgl_bina',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.alter_column('tgl_bina',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
