"""empty message

Revision ID: 3c8bf98265cb
Revises: 1cc66d7082ec
Create Date: 2023-10-17 17:00:01.669975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c8bf98265cb'
down_revision = '1cc66d7082ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_jadwal_mengajar', schema=None) as batch_op:
        batch_op.alter_column('kode_mengajar',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_jadwal_mengajar', schema=None) as batch_op:
        batch_op.alter_column('kode_mengajar',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
