"""empty message

Revision ID: 43fdd2014e66
Revises: 6aeef0ce86ed
Create Date: 2023-08-20 20:29:17.964080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fdd2014e66'
down_revision = '6aeef0ce86ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
