"""empty message

Revision ID: 4db6f0ebfa5b
Revises: 058455f2a037
Create Date: 2023-08-30 19:57:13.847019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4db6f0ebfa5b'
down_revision = '058455f2a037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pertemuan_ke', sa.Integer(), nullable=True))
        batch_op.drop_column('pertemuan_Ke')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pertemuan_Ke', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('pertemuan_ke')

    # ### end Alembic commands ###
