"""empty message

Revision ID: 576658b13cb6
Revises: 4255e037be45
Create Date: 2023-08-18 22:44:19.254958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576658b13cb6'
down_revision = '4255e037be45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siswa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('data_pembinaan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detail_siswa', ['siswa_id'], ['id'])
        batch_op.create_foreign_key(None, 'data_pelanggaran', ['pelanggaran_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_pembinaan_ibfk_1', 'data_pelanggaran', ['pelanggaran_id'], ['id'])
        batch_op.drop_column('siswa_id')

    # ### end Alembic commands ###
