"""empty message

Revision ID: 8bd038e6b8ca
Revises: 4db6f0ebfa5b
Create Date: 2023-08-30 19:58:31.950118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd038e6b8ca'
down_revision = '4db6f0ebfa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pertemuan_ke', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.drop_column('pertemuan_ke')

    # ### end Alembic commands ###
