"""empty message

Revision ID: 8c698d02e5e3
Revises: 43fdd2014e66
Create Date: 2023-08-20 20:37:49.352539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c698d02e5e3'
down_revision = '43fdd2014e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=2),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
