"""empty message

Revision ID: 8e9eae5bc55c
Revises: b4a3a0e279cb
Create Date: 2023-09-02 01:40:48.582751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9eae5bc55c'
down_revision = 'b4a3a0e279cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pertemuan_ke', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.drop_column('pertemuan_ke')

    # ### end Alembic commands ###
