"""empty message

Revision ID: 903eeedfa918
Revises: 30744b5a05c4
Create Date: 2023-08-19 12:38:47.011894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '903eeedfa918'
down_revision = '30744b5a05c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sub_tata_tertib1', schema=None) as batch_op:
        batch_op.drop_constraint('data_sub_tata_tertib1_ibfk_1', type_='foreignkey')
        batch_op.drop_column('t_tertib_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_sub_tata_tertib1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('t_tertib_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('data_sub_tata_tertib1_ibfk_1', 'data_tata_tertib', ['t_tertib_id'], ['id'])

    # ### end Alembic commands ###
