"""empty message

Revision ID: 9b4d9cb64e98
Revises: b86fe18eb512
Create Date: 2023-08-19 12:44:57.463694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4d9cb64e98'
down_revision = 'b86fe18eb512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_tata_tertib', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length='16'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_tata_tertib', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
