"""empty message

Revision ID: a18ef20fce79
Revises: 2661e21ee457
Create Date: 2023-09-13 09:13:46.061548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18ef20fce79'
down_revision = '2661e21ee457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_constraint('data_pembinaan_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detail_siswa', ['siswa_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pembinaan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_pembinaan_ibfk_3', 'detail_siswa', ['siswa_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
