"""empty message

Revision ID: b4a3a0e279cb
Revises: 8bd038e6b8ca
Create Date: 2023-09-02 01:37:19.161886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a3a0e279cb'
down_revision = '8bd038e6b8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pertemuan_ke', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_absensi', schema=None) as batch_op:
        batch_op.drop_column('pertemuan_ke')

    # ### end Alembic commands ###
