"""empty message

Revision ID: b86fe18eb512
Revises: e93fe20c9387
Create Date: 2023-08-19 12:40:37.915266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86fe18eb512'
down_revision = 'e93fe20c9387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tata_tertib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tata_tertib', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_sub_tata_tertib1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sub_tata_tertib1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tata_tertib', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('data_tata_tertib')
    # ### end Alembic commands ###
