"""empty message

Revision ID: bac8c05ec08c
Revises: 735a962d83b7
Create Date: 2023-08-23 17:37:08.529084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bac8c05ec08c'
down_revision = '735a962d83b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.drop_column('guru_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guru_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
