"""empty message

Revision ID: e93fe20c9387
Revises: 903eeedfa918
Create Date: 2023-08-19 12:40:11.280411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e93fe20c9387'
down_revision = '903eeedfa918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_teks')
    op.drop_table('data_sub_tata_tertib2')
    op.drop_table('data_tata_tertib')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tata_tertib',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tata_tertib', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_sub_tata_tertib2',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sub1_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tata_tertib', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sub1_id'], ['data_sub_tata_tertib1.id'], name='data_sub_tata_tertib2_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_teks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('teks', mysql.TEXT(), nullable=True),
    sa.Column('ket', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
