"""empty message

Revision ID: eb521ff8b41b
Revises: 1c0f311402b1
Create Date: 2023-10-02 19:00:17.772297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb521ff8b41b'
down_revision = '1c0f311402b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru_bk', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru_bk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
