"""empty message

Revision ID: efc8781a757a
Revises: eb521ff8b41b
Create Date: 2023-10-02 19:02:11.736420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc8781a757a'
down_revision = 'eb521ff8b41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru_bk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_guru_bk', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
