"""empty message

Revision ID: f9d7b75c66d6
Revises: fa7b0f719596
Create Date: 2023-08-23 17:30:59.702627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9d7b75c66d6'
down_revision = 'fa7b0f719596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.drop_constraint('data_pelanggaran_ibfk_7', type_='foreignkey')
        batch_op.drop_column('guru_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guru_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('data_pelanggaran_ibfk_7', 'detail_guru', ['guru_id'], ['id'])

    # ### end Alembic commands ###
