"""empty message

Revision ID: fa0468ac1c65
Revises: bac8c05ec08c
Create Date: 2023-08-23 17:37:37.124756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0468ac1c65'
down_revision = 'bac8c05ec08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guru_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'detail_guru', ['guru_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guru_id')

    # ### end Alembic commands ###
