"""empty message

Revision ID: fa7b0f719596
Revises: 83ce577adf07
Create Date: 2023-08-23 17:27:37.392844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7b0f719596'
down_revision = '83ce577adf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.drop_constraint('data_pelanggaran_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detail_guru', ['guru_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pelanggaran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_pelanggaran_ibfk_4', 'detail_guru', ['guru_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
